projects:
  lifeimpressionsapp:
    schemaPath: amplify/backend/api/lifeimpressionsapp/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: null
        maxDepth: 10
